<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Services\PythonApiService;

class TestPythonApi extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:python-api {--verbose}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Test Python API connection and endpoints';

    protected PythonApiService $pythonApi;

    public function __construct(PythonApiService $pythonApi)
    {
        parent::__construct();
        $this->pythonApi = $pythonApi;
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('🧪 Testing Python API Connection...');
        $this->newLine();

        $allPassed = true;

        // Test 1: Health Check
        $this->info('1️⃣  Testing Health Check...');
        $healthResult = $this->pythonApi->healthCheck();
        
        if ($healthResult['success'] ?? false) {
            $this->line('   ✅ Health check passed');
            if ($this->option('verbose')) {
                $this->line('   Response: ' . json_encode($healthResult['data'] ?? [], JSON_PRETTY_PRINT));
            }
        } else {
            $this->error('   ❌ Health check failed: ' . ($healthResult['error'] ?? 'Unknown error'));
            $allPassed = false;
        }
        $this->newLine();

        // Test 2: Get Cities
        $this->info('2️⃣  Testing Get Cities...');
        $citiesResult = $this->pythonApi->getCities(5);
        
        if ($citiesResult['success'] ?? false) {
            $count = count($citiesResult['cities'] ?? []);
            $this->line("   ✅ Get cities passed (found {$count} cities)");
            
            if ($this->option('verbose') && !empty($citiesResult['cities'])) {
                $this->line('   First city: ' . json_encode($citiesResult['cities'][0], JSON_PRETTY_PRINT));
            }
        } else {
            $this->error('   ❌ Get cities failed: ' . ($citiesResult['error'] ?? 'Unknown error'));
            $allPassed = false;
        }
        $this->newLine();

        // Test 3: Get Recommendations (if we have a city)
        if (!empty($citiesResult['cities'][0]['city_id'])) {
            $this->info('3️⃣  Testing Get Recommendations...');
            $cityId = $citiesResult['cities'][0]['city_id'];
            $cityName = $citiesResult['cities'][0]['name'] ?? 'Unknown';
            
            $this->line("   Using city: {$cityName} ({$cityId})");
            
            $preferences = [
                'destination_city_id' => $cityId,
                'guest_count' => 2,
                'duration_days' => 3,
                'target_budget' => 1500.0,
                'liked_transport_modes' => ['taxi', 'walk'],
                'disliked_transport_modes' => [],
            ];

            $this->line('   Sending request to Python API (this may take 30-60 seconds)...');
            
            $recommendationResult = $this->pythonApi->getRecommendations($preferences);
            
            if ($recommendationResult['success'] ?? false) {
                $this->line('   ✅ Get recommendations passed');
                
                $tourInfo = $recommendationResult['data']['tour_info'] ?? null;
                if ($tourInfo) {
                    $this->line('   Tour ID: ' . ($tourInfo['tour_id'] ?? 'N/A'));
                    $this->line('   Total Cost: $' . number_format($tourInfo['total_estimated_cost'] ?? 0, 2));
                    $this->line('   Days: ' . ($tourInfo['duration_days'] ?? 0));
                    $this->line('   Generated by: ' . ($tourInfo['generated_by'] ?? 'N/A'));
                }
                
                $summary = $recommendationResult['data']['summary'] ?? null;
                if ($summary) {
                    $this->line('   Total Activities: ' . ($summary['total_activities'] ?? 0));
                    $this->line('   Budget Utilized: ' . number_format($summary['budget_utilized'] ?? 0, 2) . '%');
                }
                
                if ($this->option('verbose')) {
                    $this->newLine();
                    $this->line('   Full response:');
                    $this->line(json_encode($recommendationResult, JSON_PRETTY_PRINT));
                }
            } else {
                $this->error('   ❌ Get recommendations failed: ' . ($recommendationResult['error'] ?? 'Unknown error'));
                $allPassed = false;
            }
        } else {
            $this->warn('3️⃣  Skipping recommendations test (no cities available)');
        }
        
        $this->newLine();
        $this->newLine();
        
        // Summary
        if ($allPassed) {
            $this->info('🎉 All tests passed! Python API is working correctly.');
            return Command::SUCCESS;
        } else {
            $this->error('⚠️  Some tests failed. Please check the Python API configuration.');
            $this->newLine();
            $this->line('💡 Troubleshooting:');
            $this->line('   1. Make sure Python API is running: python python_api/main.py');
            $this->line('   2. Check PYTHON_API_URL in .env (default: http://localhost:8000)');
            $this->line('   3. Verify PYTHON_API_KEY matches between Laravel and Python .env files');
            $this->line('   4. Check storage/logs/laravel.log for detailed error messages');
            
            return Command::FAILURE;
        }
    }
}

